// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/index.tsx";
import * as $1 from "./routes/posts/[post].tsx";
import * as $2 from "./routes/posts/index.tsx";
import * as $3 from "./routes/series/[seriesSlug].tsx";
import * as $4 from "./routes/series/index.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
    "./routes/posts/[post].tsx": $1,
    "./routes/posts/index.tsx": $2,
    "./routes/series/[seriesSlug].tsx": $3,
    "./routes/series/index.tsx": $4,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
